const dishes = [
    'Bacalhau à Brás',
    'Bacalhau com Natas',
    'Feijoada à Transmontana',
    'Francesinha',
    'Bacalhau à Gomes de Sá',
    'Arroz de Marisco',
    'Alheiras',
    'Cozido à Portuguesa',
    'Polvo à Lagareiro',
    'Bifana',
    'Carne de Porco à Alentejana',
    'Pica-Pau',
    'Robalo à Zé do Pipo',
    'Açorda à Alentejana',
    'Caldeirada',
    'Dourada Grelhada',
    'Feijão Verde com Ovo',
    'Empadão de Carne',
    'Leitão à Bairrada',
    'Arroz de Pato',
    'Bolinho de Bacalhau',
    'Lulas Recheadas',
    'Arroz de Tamboril',
    'Migas à Alentejana',
    'Tripas à Moda do Porto',
    'Sopa de Cação',
    'Moelas à Portuguesa',
    'Camarão à Guilho',
    'Feijão Tropeiro',
    'Conquilhas à Bulhão Pato',
    'Papas de Milho',
    'Carne de Porco com Amêijoas',
    'Bacalhau à Lagareiro',
    'Caldo Verde com Feijão',
    'Arroz de Feijão',
    'Espetadas',
    'Frango à Piri-Piri',
    'Sopa de Pedra',
    'Alcatra à Moda da Terceira',
    'Tasca de Choco Frito',
    'Arroz de Polvo',
    'Cozido de Grão',
    'Feijão com Leitão',
    'Cabrito Assado',
    'Arroz de Pato com Chouriço',
    'Prego no Pão',
    'Carne de Porco à Alentejana',
    'Bacalhau à Portuguesa',
    'Carapaus à espanhola',
    'Cocó'
]
const getRandomDish = () => {
    const randomIndex = Math.floor(Math.random() * dishes.length)
    return dishes[randomIndex]
}